server:
  port: 8791
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8790/eureka/
spring:
  application:
    name: jwt-user-authentication
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@javaproject.cmugb.mongodb.net/dealsandcoupons?retryWrites=true&w=majority